name: build

on:
  push:
  pull_request:
  schedule:
    - cron: "51 3 * * 6" # Runs at 03:51, only on Saturday
jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: ["ubuntu", "macos", "windows"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      - name: Install dependencies
        run: shards install --without-development --release
      - name: Build executable
        run: shards build --release
      - uses: actions/upload-artifact@v4
        with:
          name: sdust-${{ matrix.os }}
          path: bin/${{ matrix.os == 'windows' && 'sdust.exe' || 'sdust' }}
